In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print("\n array element type:",a.dtype)
print("\n shape of array:",a.shape)
print("\n size of array:",a.size)
reversed=a[::-1]
print(reversed)
slice1=a[2:7]
print(a[a>7])


 array element type: int32

 shape of array: (10,)

 size of array: 10
[10  9  8  7  6  5  4  3  2  1]
[ 8  9 10]


In [6]:
arr=np.array([[3,1,7],[4,2,9],[10,6,2],[11,2,5]])
newarr=arr.reshape([3,4])
print("\n reshaped array:\n",newarr)
a=np.array([[7,3,1],[9,4,2],[6,10,2],[11,5,2]])
print(np.sort(a))
slice1=arr[2:6]
print(slice1)
col=arr[:,0]
print(col)
row=arr[1,:]
print(row)


 reshaped array:
 [[ 3  1  7  4]
 [ 2  9 10  6]
 [ 2 11  2  5]]
[[ 1  3  7]
 [ 2  4  9]
 [ 2  6 10]
 [ 2  5 11]]
[[10  6  2]
 [11  2  5]]
[ 3  4 10 11]
[4 2 9]
