In [1]:
import numpy as np
a=np.array([10,20,30,40,50])
print ("one dimentinal array:",a)


one dimentinal array: [10 20 30 40 50]


In [2]:
import numpy as np
a=np.array([[10,20,30,40,50,],[60,70,80,90,100]])
print ("two dimential array:",a)

two dimential array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [3]:
import numpy as np 
c=np.zeros((3,5))
print("\n Array with all zero:\n",c)


 Array with all zero:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
import numpy as np
c=np.random.random((2,2))
print("\n Random value :\n",c) 



 Random value :
 [[0.05678255 0.6736792 ]
 [0.25912501 0.23302842]]


In [5]:
import numpy as np
s=np.arange (25,500,100)
print("\n Range value :\n",s)


 Range value :
 [ 25 125 225 325 425]


In [6]:

import numpy as np
arr=np.array([[1,2,3,9],[4,5,6,3],[7,8,9,6]])
newarr=arr.reshape ((4,3))
print("\n original array\n",arr)
print("\n Reshape array[4,3] \n",newarr)



 original array
 [[1 2 3 9]
 [4 5 6 3]
 [7 8 9 6]]

 Reshape array[4,3] 
 [[1 2 3]
 [9 4 5]
 [6 3 7]
 [8 9 6]]


In [8]:
import numpy as np
a=np.zeros((5,3))
c=np.random.random((5,3))
c=np.arange(1,10,1)
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[6,2,4],[1,4,3]])
d=arr.reshape((3,5))
print("\n Array with all zero:\n",a)
print("\n Random value :\n",c) 
print("\n Range value :\n",c)
print("\n Reshape array:\n",newarr)





 Array with all zero:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Random value :
 [1 2 3 4 5 6 7 8 9]

 Range value :
 [1 2 3 4 5 6 7 8 9]

 Reshape array:
 [[1 2 3]
 [9 4 5]
 [6 3 7]
 [8 9 6]]


In [9]:
import numpy as n
arr=np.array([[1,2,3],[4,5,6],[1,4,3]])
flat=arr.flatten()
print("Flatten array:\n",flat)

Flatten array:
 [1 2 3 4 5 6 1 4 3]


In [10]:
import numpy as np
arr=np.array([[2,4,6,],[4,8,2]])
print("\n No.of dimensions :",arr.ndim)


 No.of dimensions : 2


In [2]:
import numpy as np 
arr=np.array([[2,6,8],[4,8,2]])
print("\n Array element type:",arr.dtype)


 Array element type: int32


In [3]:
import numpy as np 
arr=np.array([[2,6,8],[4,8,2]])
newtype=arr.astype('f')
print("\n covert array element :\n",newtype)
print("\n coverted array:",newtype.dtype)


 covert array element :
 [[2. 6. 8.]
 [4. 8. 2.]]

 coverted array: float32


In [8]:
import numpy as np 
arr=np.array([[2,6,8],[4,8,2]])
print("\n size of array :\n",arr.size)


 size of array :
 6
