In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
reverse=arr[::-1]
print(reverse)

[9 8 7 6 5 4 3 2 1]


In [14]:

arr=np.array([[1,2,3],[6,7,8],[1,4,3]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [7 8]]


In [18]:
arr=np.array([[1,2,3],[6,7,8],[1,4,3]])
col=arr[:,0]
print(col)

[1 6 1]


In [20]:
arr=np.array([[1,2,3],[6,7,8],[1,4,3]])
row=arr[1,:]
print(row)

[6 7 8]


In [21]:
arr=np.array([[1,2,3],[6,7,8],[1,4,3]])
print(arr[0,0])
print(arr[1,2])

1
8


In [23]:
arr=np.array([10,20,30,40,50])
print(arr[1:4])


[20 30 40]


In [24]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])


[30 40 50]


In [25]:
arr=np.array([10,20,30,40,50])
print(arr[1])

20


In [26]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [28]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [30]:
arr1=np.array([[1,2,3,4,5]])
result=np.array_split(arr,3)
print(result)

[array([10, 20]), array([30, 40]), array([50])]
